[package]
name = "enc_rust"
version = "0.1.0"
edition = "2021"
authors = ["supinie <joshua@supinie.com>"]

description = "A rust implementation of the PQC scheme Crystals (https://pq-crystals.org/)"
readme = "README.md"

repository = "https://github.com/supinie/enc_rust"

license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# arrayvec = { version = "0.7.4", default-features = false, features = ["zeroize"] }
byteorder = "1.4.3"
# clap = { version = "4.3.12", features = ["cargo"] }
more-asserts = "0.3.1"
num_enum = { version = "0.7.1", default-features = false }
sha3 = "0.10.8"
tinyvec = "1.6.0"

[dev-dependencies]
rand = "0.8.5"
proptest = "1.4.0"


# [workspace]
# members = ["src/kyber"]
# default-members = ["src/kyber"]
